# Generated by Django 5.0.7 on 2024-07-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
